Feature/custom button
Bondar86/SkillboxDrive pull request #3
Opened 2024-02-13 16:34 UTC by Bondar86

Создал кастомную кнопку.

2024-02-14 14:17 UTC, Sinordi requested changes

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +    enum ButtonType {
Все таки много места занимает тут, можно вынести в отдельный файл (PrimaryButtonViewModel) - и оба файла закинуть в папку (PrimaryButton)

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +            if isHighlighted {
`
override var isHighlighted: Bool {
    didSet {
        // Проверяем, что у нас изменилось состояние
        guard oldValue != isHighlighted else { return }
        // Анимируем скейл (если isHighlighted - скейл будет CGAffineTransform(scaleX: 0.97, y: 0.97), если нет, тогда identity)
        UIView.animate(withDuration: 0.3) {
            self.transform = self.isHighlighted ? CGAffineTransform(scaleX: 0.97, y: 0.97) : .identity
        }
        // Анимируем альфу
        alpha = isHighlighted ? 0.4 : 1.0
    }
}
`

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +            if isHighlighted {
Капец тут в гите неудобный код

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +final class PrimaryButton: UIButton {
Добавить марки (// MARK: - Public Properties, Private Properties, Initializers, Public Methods, Private Methods

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +    private func transformIn() {
Можно будет удалить

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +    private func transformOut() {
И это

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +    private func transformIn() {
Хотя если была бы сложнее анимация, то правильно ее так и выносить в отдельный метод, но тут она не длинная, поэтому можно и так

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +        widthAnchor.constraint(equalToConstant: type.size.width).isActive = true
Лучше сделать через  intrinsicContentSize

`
 override var intrinsicContentSize: CGSize {
    type.size
 }
`

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +        widthAnchor.constraint(equalToConstant: type.size.width).isActive = true
translatesAutoresizingMaskIntoConstraints = false наверное лучше удалить от сюда и все таки определять это уже там, где ты будешь создавать кнопку. Потому что если допустим ты захочешь поместить ее в UIStackView - то у тебя  translatesAutoresizingMaskIntoConstraints - не должен быть false

2024-02-14 14:17 UTC, Sinordi commented on SkillboxDrive/Presentation/CustomViews/PrimaryButton.swift
> +        var textColor: UIColor {
Можно сделать опциональным значением и не делать так:  R.color.customBlack() ?? UIColor.black, а просто  R.color.customBlack()

2024-02-15 15:15 UTC, merged

2024-02-15 15:16 UTC, Bondar86 commented
Merge