LoginScreen
Bondar86/SkillboxDrive pull request #4
Opened 2024-02-26 15:53 UTC by Bondar86

Сверстал loginScreen. Добавил анимацию появления кнопки, акшен на кнопке принтит Text.

2024-02-26 18:02 UTC, Sinordi requested changes

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/AppViewController/AppViewController.swift
> +//        let rootViewController = createTabBarController()
Закоментированного кода не должно быть в ПР (ну кроме тех случаев, когда это оправдано и описано)

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +class LoginScreenController: UIViewController {
final

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +class LoginScreenController: UIViewController {
Ты вроде бы спрашивал, нужно ли разбивать этот модуль на MVC модули - лучше разбить)

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +    private lazy var image: UIImageView = {
Зачем ленивое (lazy) свойство?

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +    private lazy var image: UIImageView = {
можно просто private let

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +    private lazy var button = PrimaryButton(type: .normal, text: "Войти")
private let

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +        view.addSubview(button)
view.addSubview(image)
        view.addSubview(button)
        
        пусть они будут вынесены в отдельный метод addSubviews

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +        button.alpha = 0
Вообще вот это
        button.translatesAutoresizingMaskIntoConstraints = false
        button.addTarget(self, action: #selector(action), for: .touchUpInside)
        button.alpha = 0
        
        можно вынести туда. где ты создаешь саму кнопку
       И тогда там действительно будет смысл сделать ее lazy var 
       
       private lazy var button: PrimaryButton = {
          let button = PrimaryButton(...)
          button.translatesAutoresizingMaskIntoConstraints = false
          button.addTarget(self, action: #selector(action), for: .touchUpInside)
          button.alpha = 0
       }()

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +        button.alpha = 0
Ну и тогда  private func setupButton() можно переименовать, пусть будет что-то типо animateButton()

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenView.swift
> +class LoginScreenView: UIView {
А че ты созда, но не использовал то :Р

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenView.swift
> +class LoginScreenView: UIView {
Модель пока что действительно будет пустая, но view надо сделать + добавить сделать LoginScreenController делегатом для LoginScreenView

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenView.swift
> +class LoginScreenView: UIView {
final class

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenView.swift
> +class LoginScreenView: UIView {
Ты помнишь про делегаты?

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/AppViewController/AppViewController.swift
> +        lastFilesController.tabBarItem.image = R.image.lastFiles()
👍

2024-02-26 18:02 UTC, Sinordi commented on SkillboxDrive/Presentation/AppViewController/AppViewController.swift
> +        let rootViewController = loginScreenController
Надо бы подумать, как это сделать тут все по красоте

2024-02-27 14:54 UTC, Bondar86 commented on SkillboxDrive/Presentation/AppViewController/AppViewController.swift
> +        lastFilesController.tabBarItem.image = R.image.lastFiles()
Я тут ничего не делал:)

2024-02-27 14:55 UTC, Bondar86 commented on SkillboxDrive/Presentation/AppViewController/AppViewController.swift
> +//        let rootViewController = createTabBarController()
Убрал

2024-02-27 14:55 UTC, Bondar86 commented on SkillboxDrive/Presentation/AppViewController/AppViewController.swift
> +        let rootViewController = loginScreenController
хм

2024-03-07 10:49 UTC, Sinordi approved these changes

2024-03-07 10:49 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +        loadView()
loadView() - это зачем тут?

2024-03-07 10:49 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +        view = loginScreenView
Это относиться к Life Cycle, методы жизненного цикла должны идти по порядку

2024-03-07 10:49 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +    // MARK: - Public methods
Не нужен коммент тут

2024-03-07 10:49 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenController.swift
> +// MARK: - Extension
// MARK: - LoginScreenViewDelegate

2024-03-07 10:49 UTC, Sinordi commented on SkillboxDrive/Presentation/LoginScreen/LoginScreenView.swift
> +        print("ActionButton")
Можно принт убрать от сюда

2024-03-08 08:35 UTC, merged